export const GET_NOTE_LIST_SUCCESS = 'GET_NOTE_LIST_SUCCESS';
export const GET_NOTE_LIST_FAIL = 'GET_NOTE_LIST_FAIL';

export const GET_NOTE_BY_ID_SUCCESS = 'GET_NOTE_BY_ID_SUCCESS';
export const GET_NOTE_BY_ID_FAIL = 'GET_NOTE_BY_ID_FAIL';

export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const GET_NOTES_BY_CATEGORY_SUCCESS = 'GET_NOTES_BY_CATEGORY_SUCCESS';
export const GET_NOTES_BY_CATEGORY_FAIL = 'GET_NOTES_BY_CATEGORY_FAIL';

export const GET_RATES_BY_MOVIE_SUCCESS = 'GET_RATES_BY_MOVIE_SUCCESS';
export const GET_RATES_BY_MOVIE_FAIL = 'GET_RATES_BY_MOVIE_FAIL';

export const GET_WATCHLIST_SUCCESS = 'GET_WATCHLIST_SUCCESS';
export const GET_WATCHLIST_FAIL = 'GET_WATCHLIST_FAIL';